# Site settings
title: Waterhackweek 2019
email: cristn@uw.edu
description: Workshop On Water Data Science <br>
             University of Washington eScience Institute <br>
             March 25-29, 2019 <br> <br>
             Applications are open <br>
             If you would like to register click [here](https://form.jotform.com/geohack/2018).
             Successful applicants will pay a $100 registration fee and be expected to cover lodging and travel expenses. Financial support may be available based on need <br>
             #Announcements will be made shortly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/waterhackweek
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://waterhackweek2019.slack.com
twitter_url:
email_url: fwi@uw.edu

# Build settings
markdown: kramdown

